version: '3'

services:
  phoenix:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: deconfinement
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/deps/
      - /app/_build/
  db:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
